In [3]:
import pandas as pd
import numpy as np

In [49]:
url = '''https://www.pro-football-reference.com/play-index/pgl_finder.cgi?request=1&match=game&year_min=2009&year_max=2019&season_start=1&season_end=-1&pos%5B%5D=QB&is_starter=E&game_type=E&career_game_num_min=1&career_game_num_max=400&qb_start_num_min=1&qb_start_num_max=400&game_num_min=0&game_num_max=99&week_num_min=0&week_num_max=99&c1stat=fumbles&c1comp=gt&c5val=1.0&order_by=pass_yds&offset=0'''

df = pd.read_html(url)[0]
df.head(2)

df.to_csv('testing121212')

In [46]:
                                                                                                                                                                                                                                                                                                                                                                                                                                         
passing_list = []
for i in range(0, 7100, 100):
    url = '''https://www.pro-football-reference.com/play-index/pgl_finder.cgi?request=1&match=game&year_min=2009&year_max=2019&season_start=1&season_end=-1&pos%5B%5D=QB&is_starter=E&game_type=E&career_game_num_min=1&career_game_num_max=400&qb_start_num_min=1&qb_start_num_max=400&game_num_min=0&game_num_max=99&week_num_min=0&week_num_max=99&c1stat=fumbles&c1comp=gt&c5val=1.0&order_by=pass_yds&offset={}'''
    
    passing_list.append(pd.read_html(url.format(i), skiprows=0, header=1)[0])
#passing_stats = pd.concat(passing_list)
# passing_stats.to_csv('passing_stats')

In [47]:
passing_stats = pd.concat(passing_list)

In [48]:
passing_stats[159:210]

,Rk,Player,Pos,Age,Date,Lg,Tm,Unnamed: 7,Opp,Result,...,Sk,Yds.1,Y/A,AY/A,Fmb,FL,FF,FR,Yds.2,TD.1
55,154,Eli Manning,QB,35.287,2016-10-16,NFL,NYG,NaN,BAL,W 27-23,...,1,6,8.76,8.11,0,0,0,0,0,0
56,155,Peyton Manning,QB,37.252,2013-12-01,NFL,DEN,@,KAN,W 35-28,...,0,0,11.51,11.80,0,0,0,0,0,0
57,156,Philip Rivers,QB,33.279,2015-09-13,NFL,SDG,NaN,DET,W 33-28,...,2,16,9.83,8.61,0,0,0,0,0,0
58,157,Ryan Fitzpatrick,QB,31.021,2013-12-15,NFL,TEN,NaN,ARI,L 34-37,...,3,8,6.93,6.76,1,0,0,0,0,0
59,158,Ryan Fitzpatrick,QB,35.296,2018-09-16,NFL,TAM,NaN,PHI,W 27-21,...,2,9,12.18,13.24,0,0,0,0,0,0
60,159,Deshaun Watson,QB,22.045,2017-10-29,NFL,HOU,@,SEA,L 38-41,...,5,35,13.40,11.57,0,0,0,0,0,0
61,160,Philip Rivers,QB,31.295,2013-09-29,NFL,SDG,NaN,DAL,W 30-21,...,1,7,9.55,9.90,0,0,0,0,0,0
62,Rk,Player,Pos,Age,Date,Lg,Tm,NaN,Opp,Result,...,Sk,Yds,Y/A,AY/A,Fmb,FL,FF,FR,Yds,TD
63,161,Philip Rivers,QB,36.345,2018-11-18,NFL,LAC,NaN,DEN,L 22-23,...,3,17,9.33,8.16,0,0,0,0,0,0
64,162,Andrew Luck,QB,25.044,2014-10-26,NFL,IND,@,PIT,L 34-51,...,2,15,8.89,8.22,1,0,0,0,0,0
65,163,Eli Manning,QB,30.342,2011-12-11,NFL,NYG,@,DAL,W 37-34,...,0,0,8.51,8.40,0,NaN,0,0,0,0
66,164,Peyton Manning,QB,37.273,2013-12-22,NFL,DEN,@,HOU,W 37-13,...,1,3,7.84,9.41,0,0,0,0,0,0
67,165,Peyton Manning,QB,37.301,2014-01-19,NFL,DEN,NaN,NWE,W 26-16,...,0,0,9.30,10.23,0,0,0,0,0,0
68,166,Ben Roethlisberger,QB,31.246,2013-11-03,NFL,PIT,@,NWE,L 31-55,...,5,29,8.33,8.13,1,1,0,0,0,0
69,167,Jameis Winston,QB,25.280,2019-10-13,NFL,TAM,NaN,CAR,L 26-37,...,7,35,7.41,3.61,2,1,0,0,0,0
70,168,Vince Young,QB,28.193,2011-11-27,NFL,PHI,NaN,NWE,L 20-38,...,2,7,8.33,7.81,0,NaN,0,0,0,0
71,169,Andrew Luck,QB,29.088,2018-12-09,NFL,IND,@,HOU,W 24-21,...,2,13,9.73,9.61,0,0,0,0,0,0
72,170,Eli Manning,QB,37.292,2018-10-22,NFL,NYG,@,ATL,L 20-23,...,4,27,10.50,11.03,0,0,0,0,0,0
73,171,Colin Kaepernick,QB,29.003,2016-11-06,NFL,SFO,NaN,NOR,L 23-41,...,1,5,10.21,10.08,1,1,0,0,0,0
74,172,Ben Roethlisberger,QB,27.265,2009-11-22,NFL,PIT,@,KAN,L 24-27,...,2,13,9.48,8.76,0,NaN,0,0,0,0
75,173,Brian Hoyer,QB,30.362,2016-10-09,NFL,CHI,@,IND,L 23-29,...,0,0,9.23,10.16,0,0,0,0,0,0
76,174,Peyton Manning,QB,37.259,2013-12-08,NFL,DEN,NaN,TEN,W 51-28,...,0,0,6.73,8.08,0,0,0,0,0,0
77,175,Baker Mayfield,QB,23.232,2018-12-02,NFL,CLE,@,HOU,L 13-29,...,0,0,9.23,6.56,0,0,0,0,0,0
78,176,Dak Prescott,QB,26.104,2019-11-10,NFL,DAL,NaN,MIN,L 24-28,...,1,4,8.63,8.96,0,0,0,0,0,0
79,177,Matt Ryan,QB,30.168,2015-11-01,NFL,ATL,NaN,TAM,L 20-23,...,1,2,8.82,8.71,2,1,0,0,-4,0
80,178,Matt Ryan,QB,34.135,2019-09-29,NFL,ATL,NaN,TEN,L 10-24,...,5,33,7.49,7.49,1,1,0,0,0,0
81,179,Drew Brees,QB,33.350,2012-12-30,NFL,NOR,NaN,CAR,L 38-44,...,2,18,9.21,10.02,0,0,0,0,0,0
82,180,Drew Brees,QB,39.251,2018-09-23,NFL,NOR,@,ATL,W 43-37,...,1,5,8.08,9.31,1,0,0,0,0,0
83,Rk,Player,Pos,Age,Date,Lg,Tm,NaN,Opp,Result,...,Sk,Yds,Y/A,AY/A,Fmb,FL,FF,FR,Yds,TD
84,181,Andy Dalton,QB,32.054,2019-12-22,NFL,CIN,@,MIA,L 35-38,...,4,25,7.07,8.50,1,1,0,0,0,0
85,182,Peyton Manning,QB,34.242,2010-11-21,NFL,IND,@,NWE,L 28-31,...,0,0,7.62,6.56,0,NaN,0,0,0,0
86,183,Aaron Rodgers,QB,27.311,2011-10-09,NFL,GNB,@,ATL,W 25-14,...,4,27,10.15,11.18,0,NaN,0,0,0,0
87,184,Matt Ryan,QB,27.248,2013-01-20,NFL,ATL,NaN,SFO,L 24-28,...,1,0,9.43,9.79,1,1,0,0,-9,0
88,185,Matt Ryan,QB,31.124,2016-09-18,NFL,ATL,@,OAK,W 35-28,...,1,7,11.65,12.09,0,0,0,0,0,0
89,186,Ryan Tannehill,QB,26.147,2014-12-21,NFL,MIA,NaN,MIN,W 37-35,...,1,13,8.43,9.17,0,0,0,0,0,0
90,187,Tom Brady,QB,35.072,2012-10-14,NFL,NWE,@,SEA,L 23-24,...,1,7,6.81,5.95,0,0,0,0,0,0
91,188,Jared Goff,QB,24.354,2019-10-03,NFL,LAR,@,SEA,L 29-30,...,0,0,8.06,7.55,0,0,0,0,0,0
92,189,Jameis Winston,QB,24.281,2018-10-14,NFL,TAM,@,ATL,L 29-34,...,2,6,9.63,9.39,2,0,0,0,0,0
93,190,Drew Brees,QB,34.334,2013-12-15,NFL,NOR,@,STL,L 16-27,...,4,22,7.02,5.77,1,1,0,0,0,0
94,191,Andrew Luck,QB,25.016,2014-09-28,NFL,IND,NaN,TEN,W 41-17,...,0,0,9.59,10.44,0,0,0,0,0,0
95,192,Matt Schaub,QB,29.171,2010-12-13,NFL,HOU,NaN,BAL,L 28-34,...,2,15,6.34,5.85,0,NaN,0,0,0,0
96,193,Drew Brees,QB,34.299,2013-11-10,NFL,NOR,NaN,DAL,W 49-17,...,1,9,9.56,11.51,0,0,0,0,0,0
97,194,Brett Favre*,QB,40.050,2009-11-29,NFL,MIN,NaN,CHI,W 36-10,...,1,14,8.17,9.42,0,NaN,0,0,0,0
98,195,Colt McCoy,QB,28.086,2014-11-30,NFL,WAS,@,IND,L 27-49,...,6,51,8.34,9.62,4,1,0,0,-1,0
99,196,Philip Rivers,QB,31.351,2013-11-24,NFL,SDG,@,KAN,W 41-38,...,1,5,10.05,11.59,0,0,0,0,0,0
100,197,Tony Romo,QB,29.229,2009-12-06,NFL,DAL,@,NYG,L 24-31,...,2,13,7.13,8.22,0,NaN,0,0,0,0
101,198,Matt Ryan,QB,31.250,2017-01-22,NFL,ATL,NaN,GNB,W 44-21,...,0,0,10.32,12.42,1,0,0,0,-3,0
102,199,Matt Schaub,QB,28.115,2009-10-18,NFL,HOU,@,CIN,W 28-17,...,2,7,9.80,10.68,0,NaN,0,0,0,0
103,200,Jason Campbell,QB,31.342,2013-12-08,NFL,CLE,@,NWE,L 26-27,...,1,5,8.89,10.25,0,0,0,0,0,0
0,201,Derek Carr,QB,28.276,2019-12-29,NFL,OAK,@,DEN,L 15-16,...,2,11,8.50,8.93,1,0,0,1,-2,0
1,202,Jared Goff,QB,24.021,2018-11-04,NFL,LAR,@,NOR,L 35-45,...,0,0,9.78,10.15,0,0,0,0,0,0

In [57]:
passing_stats.shape

(7077, 30)

In [50]:
passing_stats.columns

Index(['Rk', 'Player', 'Pos', 'Age', 'Date', 'Lg', 'Tm', 'Unnamed: 7', 'Opp',
       'Result', 'G#', 'Week', 'Day', 'Cmp', 'Att', 'Cmp%', 'Yds', 'TD', 'Int',
       'Rate', 'Sk', 'Yds.1', 'Y/A', 'AY/A', 'Fmb', 'FL', 'FF', 'FR', 'Yds.2',
       'TD.1'],
      dtype='object')

In [54]:
passing_stats.drop(passing_stats[passing_stats['Player'] == 'Player'].index, inplace=True)

In [56]:
passing_stats.shape

(7077, 30)

In [8]:
from pymongo import MongoClient
import pprint
from bs4 import BeautifulSoup, Comment
import requests
import pandas as pd
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
import math
import re
import json
import time

In [10]:
def web_scrape(url, filename):
    data = requests.get(url)
    soup = BeautifulSoup(data.text, features="lxml")
    team_data = soup.findAll(class_= 'span3 wbkg')

    table_set = set()
    for i in range(len(team_data)):
        
        date = soup.findAll('div', {'class':'gt-header'})[i].text.strip().split('\n')[0]
        away_team = soup.findAll('div', {'class':'gt-away'})[i].text.strip().split('\n')[0]
        away_team_score = soup.findAll('div', {'class':'gt-away'})[i].text.strip().split('\n')[1]
        home_team = soup.findAll('div', {'class':'gt-home'})[i].text.strip().split('\n')[0]
        home_team_score = soup.findAll('div', {'class':'gt-home'})[i].text.strip().split('\n')[1]
        weather = soup.findAll('div', {'class':'gt-weather'})[i].text.strip().split('f')[0]
        if weather == 'DOME':
            weather_temp = np.NaN
            weather_type = 'DOME'
        else:
            weather_temp = np.int(weather) if '/' not in weather else np.NaN 
            weather_type = soup.findAll('div', {'class':'gt-weather'})[i].text.strip().split('f')[1]
        game_row = (date, away_team, np.int(away_team_score), home_team, np.int(home_team_score), weather_temp, weather_type)
        table_set.add(game_row)
    table_list = list(table_set)
    df = pd.DataFrame(table_list, columns = ('Date', 'Away_Team', 'Away_Team_Score', 'Home_Team', 'Home_Team_Score', 'Weather_Temp', 'Weather_Type'))
    df.to_csv(filename)
    return None
web_scrape('http://www.nflweather.com/en/searches/104008', 'chiefs_games')

KeyboardInterrupt:

In [66]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
passing_games_list = []
for i in range(0, 1300, 100):
    url = '''https://www.pro-football-reference.com/play-index/tgl_finder.cgi?request=1&match=game&year_min=2015&year_max=2019&game_type=R&game_num_min=0&game_num_max=99&week_num_min=0&week_num_max=99&temperature_gtlt=lt&game_location=H&c5val=1.0&order_by=pass_yds&offset={}'''
    
    passing_games_list.append(pd.read_html(url.format(i), skiprows=0, header=1)[0])
#passing_stats = pd.concat(passing_list)
# passing_stats.to_csv('passing_stats')

In [67]:
game_stats = pd.concat(passing_games_list)

In [68]:
game_stats.shape

(1331, 22)

In [69]:
game_stats[0:30]

,Rk,Tm,Year,Date,Time,LTime,Unnamed: 6,Opp,Week,G#,...,OT,Cmp,Att,Cmp%,Yds,TD,Int,Sk,Yds.1,Rate
0,1,NOR,2015,2015-11-01,1:02,12:02,NaN,NYG,8,8,...,NaN,39,50,78.0,505,7,2,0,0,131.7
1,2,LAR,2019,2019-09-29,4:05,1:05,NaN,TAM,4,4,...,NaN,45,68,66.2,490,2,3,2,27,78.7
2,3,PIT,2017,2017-12-10,8:30,8:30,NaN,BAL,14,13,...,NaN,44,66,66.7,486,2,0,3,20,98.4
3,4,ATL,2016,2016-10-02,1:04,1:04,NaN,CAR,4,4,...,NaN,28,37,75.7,481,4,1,3,22,142.0
4,5,TAM,2019,2019-12-08,1:00,1:00,NaN,IND,14,13,...,NaN,35,49,71.4,467,4,3,1,7,103.0
5,6,PHI,2018,2018-12-23,1:00,1:00,NaN,HOU,16,15,...,NaN,35,50,70.0,462,4,1,1,9,117.2
6,7,NOR,2016,2016-10-16,1:03,12:03,NaN,CAR,6,5,...,NaN,34,49,69.4,460,4,1,1,5,117.7
7,8,LAR,2018,2018-09-27,8:20,5:20,NaN,MIN,4,4,...,NaN,26,34,76.5,456,5,0,1,9,157.5
8,9,SEA,2017,2017-10-29,4:05,1:05,NaN,HOU,8,7,...,NaN,26,41,63.4,446,4,1,2,6,122.6
9,10,PIT,2018,2018-09-16,1:00,1:00,NaN,KAN,2,2,...,NaN,39,60,65.0,442,3,0,1,10,103.6
10,11,ATL,2019,2019-10-27,1:00,1:00,NaN,SEA,8,8,...,NaN,39,52,75.0,441,1,1,2,19,98.3
11,12,DAL,2019,2019-10-06,4:25,3:25,NaN,GNB,5,5,...,NaN,27,44,61.4,441,2,3,3,22,81.7
12,13,NYG,2015,2015-10-11,8:31,8:31,NaN,SFO,5,5,...,NaN,41,54,75.9,441,3,1,0,0,110.2
13,14,IND,2018,2018-09-30,1:00,1:00,NaN,HOU,4,4,...,OT,40,62,64.5,437,4,0,4,27,106.7
14,15,DAL,2018,2018-12-09,4:25,3:25,NaN,PHI,14,13,...,OT,42,54,77.8,434,3,2,3,21,103.2
15,16,NOR,2018,2018-09-09,1:00,12:00,NaN,TAM,1,1,...,NaN,37,45,82.2,432,3,0,1,7,128.9
16,17,NYG,2017,2017-12-17,1:00,1:00,NaN,PHI,15,14,...,NaN,37,57,64.9,429,3,1,1,5,97.8
17,18,HOU,2019,2019-10-06,1:00,12:00,NaN,ATL,5,5,...,NaN,28,33,84.8,426,5,0,0,0,158.3
18,19,OAK,2018,2018-09-30,4:05,1:05,NaN,CLE,4,4,...,OT,35,58,60.3,426,4,2,3,11,91.6
19,20,GNB,2019,2019-10-20,1:00,12:00,NaN,OAK,7,7,...,NaN,25,31,80.6,421,5,0,1,8,158.3
20,Rk,Tm,Year,Date,Time,LTime,NaN,Opp,Week,G#,...,OT,Cmp,Att,Cmp%,Yds,TD,Int,Sk,Yds,Rate
21,21,NOR,2016,2016-09-11,1:05,12:05,NaN,OAK,1,1,...,NaN,28,42,66.7,419,4,0,1,4,131.0
22,22,LAC,2018,2018-09-09,4:05,1:05,NaN,KAN,1,1,...,NaN,34,51,66.7,418,3,1,1,6,103.2
23,23,OAK,2017,2017-10-19,8:25,5:25,NaN,KAN,7,7,...,NaN,29,52,55.8,417,3,0,0,0,101.2
24,24,GNB,2019,2019-09-26,8:20,7:20,NaN,PHI,4,4,...,NaN,34,53,64.2,414,2,1,1,8,92.8
25,25,DAL,2015,2016-01-03,1:03,12:03,NaN,WAS,17,16,...,NaN,33,48,68.8,412,3,2,4,23,98.6
26,26,DET,2017,2017-10-29,8:30,8:30,NaN,PIT,8,7,...,NaN,27,45,60.0,411,0,0,2,12,90.1
27,27,SFO,2019,2019-11-17,4:05,1:05,NaN,ARI,11,10,...,NaN,34,45,75.6,408,4,2,2,16,113.9
28,28,MIA,2019,2019-12-22,1:00,1:00,NaN,CIN,16,15,...,OT,31,52,59.6,406,4,1,2,13,101.9
29,29,SEA,2019,2019-09-22,4:25,1:25,NaN,NOR,3,3,...,NaN,32,50,64.0,406,2,0,0,0,102.6

In [70]:
game_stats.drop(game_stats[game_stats['Tm'] == 'Tm'].index, inplace=True)

In [71]:
game_stats.shape

(1280, 22)

In [95]:
game_stats = game_stats.reset_index()

In [97]:
game_stats[90:120]

,index,Rk,Tm,Year,Date,Time,LTime,Unnamed: 6,Opp,Week,...,OT,Cmp,Att,Cmp%,Yds,TD,Int,Sk,Yds.1,Rate
90,94,91,SDG,2015,2015-10-12,8:30,5:30,NaN,PIT,5,...,NaN,35,48,72.9,354,2,1,2,11,98.8
91,95,92,CAR,2016,2016-09-18,1:03,1:03,NaN,SFO,2,...,NaN,24,40,60.0,353,4,1,1,0,111.8
92,96,93,IND,2018,2018-12-23,1:00,1:00,NaN,NYG,16,...,NaN,31,47,66.0,353,2,1,1,4,93.7
93,97,94,KAN,2018,2018-10-21,8:20,12:00,NaN,CIN,7,...,NaN,28,39,71.8,353,4,1,2,5,123.1
94,98,95,NYG,2016,2016-09-18,1:03,1:03,NaN,NOR,2,...,NaN,32,41,78.0,353,0,0,2,15,102.5
95,99,96,PHI,2015,2015-11-15,1:05,1:05,NaN,MIA,10,...,NaN,33,48,68.8,353,1,1,4,39,88.3
96,100,97,PHI,2015,2015-12-26,8:26,8:26,NaN,WAS,16,...,NaN,37,56,66.1,353,1,0,5,27,89.4
97,101,98,DET,2019,2019-10-20,1:00,1:00,NaN,MIN,7,...,NaN,30,45,66.7,352,4,1,2,12,110.6
98,102,99,MIA,2019,2019-12-01,1:00,1:00,NaN,PHI,13,...,NaN,28,40,70.0,351,4,1,3,15,119.9
99,103,100,OAK,2015,2015-09-20,4:05,1:05,NaN,BAL,2,...,NaN,30,46,65.2,351,3,1,1,0,100.9
100,0,101,PHI,2015,2015-12-20,8:31,8:31,NaN,ARI,15,...,NaN,28,41,68.3,350,2,2,2,11,90.5
101,1,102,PHI,2018,2018-11-11,8:20,8:20,NaN,DAL,10,...,NaN,32,44,72.7,350,2,1,2,10,101.5
102,2,103,LAR,2018,2018-09-23,4:05,1:05,NaN,LAC,3,...,NaN,29,36,80.6,350,3,1,1,4,123.4
103,3,104,SFO,2015,2016-01-03,4:25,1:25,NaN,STL,17,...,OT,28,44,63.6,350,1,1,1,4,86.4
104,4,105,WAS,2016,2016-09-18,1:03,1:03,NaN,DAL,2,...,NaN,28,46,60.9,350,1,1,2,14,82.7
105,5,106,NOR,2018,2018-10-08,8:15,7:15,NaN,WAS,5,...,NaN,26,29,89.7,349,3,0,2,14,151.3
106,6,107,NOR,2019,2019-12-08,1:00,12:00,NaN,SFO,14,...,NaN,29,41,70.7,349,5,0,0,0,136.1
107,7,108,CHI,2018,2018-11-11,1:00,12:00,NaN,DET,10,...,NaN,23,30,76.7,348,3,0,1,7,147.6
108,8,109,KAN,2018,2018-12-09,1:00,12:00,NaN,BAL,14,...,OT,35,53,66.0,348,2,1,3,29,89.2
109,9,110,NOR,2017,2017-09-17,1:00,12:00,NaN,NWE,2,...,NaN,27,45,60.0,348,2,0,1,8,99.1
110,10,111,ATL,2018,2018-10-14,1:00,1:00,NaN,TAM,6,...,NaN,31,41,75.6,347,3,0,1,8,124.7
111,11,112,CLE,2018,2018-12-23,1:00,1:00,NaN,CIN,16,...,NaN,28,38,73.7,347,3,0,0,0,127.9
112,12,113,JAX,2019,2019-09-08,1:00,1:00,NaN,KAN,1,...,NaN,27,33,81.8,347,3,1,1,3,128.2
113,13,114,SDG,2015,2015-10-04,4:05,1:05,NaN,CLE,4,...,NaN,23,38,60.5,347,3,0,2,11,116.9
114,14,115,SEA,2019,2019-11-03,4:05,1:05,NaN,TAM,9,...,OT,29,43,67.4,347,5,0,3,31,130.7
115,15,116,NOR,2016,2016-11-27,1:00,12:00,NaN,LAR,12,...,NaN,29,37,78.4,346,5,0,2,14,145.2
116,16,117,NOR,2018,2018-11-04,4:25,3:25,NaN,LAR,9,...,NaN,25,36,69.4,346,4,0,0,0,137.0
117,17,118,NWE,2015,2015-09-27,1:06,1:06,NaN,JAX,3,...,NaN,33,42,78.6,346,2,0,2,12,116.9
118,18,119,NOR,2019,2019-10-06,1:00,12:00,NaN,TAM,5,...,NaN,28,36,77.8,345,4,1,0,0,132.1
119,19,120,TEN,2015,2015-09-27,1:03,12:03,NaN,IND,3,...,NaN,27,44,61.4,345,2,2,3,22,82.1

In [99]:
type(game_stats['Date'][0])

str

In [72]:
game_stats.to_csv('5_years_passing_stats.csv')

In [41]:
import psycopg2 as pg2

In [74]:
df2019_weather = pd.read_csv('capstone1/2019_nfl_weather.csv')
#http://localhost:8888/edit/capstone1/2019_nfl_weather.csv

In [75]:
df2019_weather.head()

,Unnamed: 0,Date,Away_Team,Home_Team,Weather_Temp,Weather_Type
0,0,Sun 08/25/19 08:00 PM,Pittsburgh Steelers,Tennessee Titans,76.0,Light Rain
1,1,Sun 09/22/19 01:00 PM,Baltimore Ravens,Kansas City Chiefs,69.0,Overcast
2,2,Sun 12/22/19 01:00 PM,Jacksonville Jaguars,Atlanta Falcons,NaN,DOME
3,3,Mon 12/16/19 08:15 PM,Indianapolis Colts,New Orleans Saints,NaN,DOME
4,4,Sun 09/08/19 04:05 PM,Cincinnati Bengals,Seattle Seahawks,66.0,Overcast

In [102]:
from datetime import datetime
datetime.strptime(df2019_weather['Date'][1], '%a %m/%d/%y %I:%M %p').strftime("%Y-%m-%d")

'2019-09-22'

In [76]:
dictionary for team names and abbreviations
convert the date to yearr-month-day

SyntaxError: invalid syntax (<ipython-input-76-6ee74511a590>, line 1)

In [77]:
df2019_weather.columns

Index(['Unnamed: 0', 'Date', 'Away_Team', 'Home_Team', 'Weather_Temp',
       'Weather_Type'],
      dtype='object')

In [ ]:
import datetime
def date_stripper():
    

df2019_weather['Date'] = df2019_weather['Date'].apply()

In [ ]:
import datetime
x = datetime.datetime(2018, 9, 15)
print(x.strftime("%Y-%m-%d"))